### ISSUE TITLE
Problems discovering/running tests in NHibernate.Spatial using Visual Studio 2015

### ISSUE THREAD

**Issue by andrerav** [nunit/nunit-vs-adapter#100]
Hi,

I am trying to use this adapter to run the tests in the [NHibernate.Spatial](https://github.com/nhibernate/NHibernate.Spatial) project. However, after installing this adapter and building the project I get an unexpected selection of tests to run:

![Test Explorer](http://i.imgur.com/FGiel5q.png)

I expected a roughly equal number of tests from three different projects: Tests.NHibernate.Spatial.MsSql2008, Tests.NHibernate.Spatial.MySql, 
and Tests.NHibernate.Spatial.PostGis.

I assume that this is either a configuration error in the solution, or a user error, and I am looking for guidance on how to fix this problem. Any help will be greatly appreciated not just by me but also anyone else who wants to work on NHibernate.Spatial :)

**Comment by CharliePoole** [comment]
Is there anything different or unusual about the 710 classes listed as External?

Do tests show up as expected using other sorts than by project?

**Comment by andrerav** [comment]
@CharliePoole To answer your first question: I'm not really sure what to look for. All the tests inherit from common base test classes in Tests.NHibernate.Spatial, and I can execute them just fine using Resharper. 

To answer your second question, here's another screenshot sorted by class. This is not really what I expect. It also says "no source available" so I can't navigate to the test source code by clicking on the test name.

![Screenshot](http://i.imgur.com/84y7a43.png)

**Comment by OsirisTerje** [comment]
On the no source thing, do you run this in Debug or Release?  If in Release, do the ones with no source have no pdb files being generated ?

**Comment by andrerav** [comment]
@OsirisTerje Debug only. The test case here is readily available; simply clone the repo and try it yourself ;)

**Comment by OsirisTerje** [comment]
Notice the project has now moved to NUnit3.
