### ISSUE TITLE
"Source: no source available" for tests in abstract base class

### ISSUE THREAD

**Issue by drmannion** [nunit/nunit-vs-adapter#101]
Test methods defined on an abstract base class are properly included under the derived class in Test Explorer and run as expected.  However, you can not open the test method source code for the base class methods from Test Explorer by double clicking or by pressing F12.  Test Explorer shows the following message: "Source: no source available"
![untitled picture](https://cloud.githubusercontent.com/assets/12001392/13787717/49bfd262-ea9a-11e5-9ff5-eb46ee6184e1.png)

**Comment by rprouse** [comment]
This may also happen in this adapter, but according to your output, this should be reported against the v3 adapter.

**Comment by drmannion** [comment]
My mistake.  I'll post against the v3 adapter as well.

**Comment by rprouse** [comment]
I am going to close this as no-repro. Make sure you have the latest version of the adapter installed, it might have been fixed.

I have the following code,

```C#
[TestFixture]
public abstract class AbstractGenericBase<T>
{
    [Test]
    public void AbstractGenericBaseTest()
    {
        Assert.Pass("AbstractGenericBase");
    }

    public abstract void MustImplement();
}

[TestFixture]
public class DerivedAbstractGeneric : AbstractGenericBase<string>
{
    [Test]
    public void DerivedAbstractGenericTest()
    {
        Assert.Pass("DerivedAbstractGeneric");
    }

    public override void MustImplement()
    {
    }
}
```

And I can see and click on the source and it goes to the correct location,

![image](https://cloud.githubusercontent.com/assets/493828/19403087/db805808-9232-11e6-9f32-7ac69d6fb97a.png)
