### ISSUE TITLE
UnsupportedFrameworkException When running Tests.

### ISSUE THREAD

**Issue by feinstein** [nunit/nunit-vs-adapter#102]
I upgraded my project from Visual Studio 2013 to 2015, than I upgraded my NUnit from the 2.0 to the most recent version 3.2.0 and I installed the  NUnit Test Adapter for VS2015.

When I select to run all tests, I get this message on my Output:

```
------ Run test started ------
NUnit VS Adapter 2.0.0.0 executing tests is started
Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in M:\...........Tests.dll
NUnit VS Adapter 2.0.0.0 executing tests is finished
========== Run test finished: 3 run (0:00:03,566204) ==========
```

**Comment by CharliePoole** [comment]
You should be using the NUnit __3__ VS adapter with NUnit 3.

**Comment by feinstein** [comment]
Oh, that makes lots of sense hahaha, it isn't on Google's first search results.

I see there is an [adapter ](https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d) and a [Nuget ](https://www.nuget.org/packages/NUnit3TestAdapter/3.0.8-ctp-8) version as well, are they the same?

**Comment by CharliePoole** [comment]
You can download both adapters (2.0 and 3.0) as either a vsix extension for global installation in visual studio or as nuget packages for installing in a single solution. If you still have test projects using NUnit V2 as well as V3, the nuget package may make more sense.

**Comment by prakash9pandu09** [comment]
I have installed Nunit 3 and Nunit3TestAdaptor and i am getting an error during TFS build
Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in D:\Builds\8\349\bin\MVCProject.Tests.dll. i have uninstalled all nunit 2.0 related dlls.
can anyone help me how to resolve this exception

**Comment by OsirisTerje** [comment]
@prakash9pandu09  You need to give us a little bit more details.  
Also, how does it work locally.  Version...  Types of project... 
Did it work before?
