### ISSUE TITLE
Tests do not display in the Test pane of VS2015

### ISSUE THREAD

**Issue by nambrose** [nunit/nunit-vs-adapter#104]
I think this is due to a corrupt NUnit file or state somewhere because it was working fine and then stopped.

What happens is we have some NUnit tests and some Visual Studio tests
When I Select the Test Explorer pane and exit VS then restart it, a list of tests briefly displays (I *think* it might just show the VS style tests) then the list becomes blank and never shows any more tests.

I see this at the end of test discovery

NUnit VS Adapter 2.0.0.0 discovering test is finished
Model compatibility cannot be checked because the database does not contain model metadata. Ensure that IncludeMetadataConvention has been added to the DbModelBuilder conventions.
========== Discover test finished: 3319 found (0:00:16.475135) ==========

I tried to uninstall and re-install the adapter but no luck. These tests display fine for other users on VS2015

I think something is corrupted but I dont know what to clean out. I did clean the "Cache/Temp" files but it did not help

**Comment by OsirisTerje** [comment]
This seems to be an error from EF5.  Have you checked the answers in http://stackoverflow.com/questions/14064434/ef5-getting-this-error-message-model-compatibility-cannot-be-checked-because-th ?    The adapter should still show the test list, so something more might be going on. Can you turn on the verbose setting?  See https://github.com/nunit/nunit-vs-adapter/wiki/Tips-And-Tricks  Further, check that you are running correctly x86/x64, using the "wrong" one tend to have the same sympton, tests not appearing. See under Test/Test Settings/Default Architecture and choose appropriate x86 or x64 there.

**Comment by nambrose** [comment]
Thanks for the response. I checked out both articles.

The EF one I am not sure about. The VM where the tests work doesn't have anything like that and neither does my non-functioning machine.

I tried to enable logging but I dont have a registry key like nunit.org on either machine. Do I just add that manually ?

Both adapters are set to type=X86 for the architecture

Its super weird as I *do* get a (partial?) list and then it disappears.
I dont think the list is complete because the #'s of tests reported are too small but it's hard to say when it disappears

**Comment by nambrose** [comment]
Actually what I should do here is make a new project and see if I can get any tests to show there.
Let me see if I can do that and see what happens.

Further advice on enabling verbose logging would be appreciated too.

Adapter version is 2.0.0.0

**Comment by OsirisTerje** [comment]
To set verbose, you add the key manually, yes

**Comment by nambrose** [comment]
Hmmm, so I added the key but I dont see any different output.
At the end it does say this:
========== Discover test finished: 3819 found (0:00:17.0085075) ==========

But no tests in my list!

Creating a new project with a single test did work and the test showed up so It must be project-specific however I've blown away my local working directory and re-synced up and still nothing.

Super odd

**Comment by OsirisTerje** [comment]
That's ok.  Just means the adapter doesn't trigger on anything that would give out a verbose message.  If you could manage to create a repro project and upload it somewhere, we could have a look at what is happening here.

**Comment by nambrose** [comment]
I'll definitely try to do that but its looking pretty tough.
Going to close this one out now until I can find out more.
