### ISSUE TITLE
Test explorer window displays test under first trait only

### ISSUE THREAD

**Issue by tirexx** [nunit/nunit-vs-adapter#108]
VS 2015 Update2
Nunit vs adapter 3.0.10

If there are several category attributes, for example:
[NUnit.Framework.TestAttribute()]
[NUnit.Framework.CategoryAttribute("Ci")]
[NUnit.Framework.CategoryAttribute("Integration")]
public virtual void SomeTest()

In the test explorer window, when in "group by \ traits" mode. I see tests only under first category.

**Comment by rprouse** [comment]
I believe this is a limitation of the Visual Studio test window. I am pretty sure that it can only list each test once therefore tests can only be under one category. @OsirisTerje can you confirm?

**Comment by tirexx** [comment]
If so, it is a new limitation, because before 2015 update 2 and NUnit 3.* all was ok.

**Comment by CharliePoole** [comment]
What about NUnit 3.x under earlier releases of VS?

**Comment by tirexx** [comment]
I don't know. 
May be in a week i will be able to install fresh vs 2015 update 1, and check this.

**Comment by IanMcRV** [comment]
I wonder if it might be something to do with Visual Studio Update 2 ?

Otherwise the perfect mechanism for catagorising tests (i find that playlists don't work very well for my needs) but as it stands each test can be in only one category.

**Comment by CharliePoole** [comment]
This issue is reported against the nunit vs adapter (2.0) and not the nunit3 vs adapter (3.0+)

Can somebody clarify whether the problem exists in both adapters or only one? There are two different codebases for us to work on.

[We might consider combining these projects in the future, but right now they are separate.]

**Comment by tirexx** [comment]
This issue was reported against:
VS 2015 Update2
NUnit3 Test Adapter 3.0.10

**Comment by OsirisTerje** [comment]
This is an Update 2 regression of some sort. I have alerted MS about it, and waiting for a response.  And the error is with the Nunit2 adapter too. 
It is working with MSTest, however.......

**Comment by OsirisTerje** [comment]
This has been confirmed as a bug in VS 2015 update 2, and will be fixed in VS 2015 Update 3.

**Comment by tirexx** [comment]
Thanx!

**Comment by scara** [comment]
Confirmed that applying VS 2015 Update 3 fixes nunit/nunit3-vs-adapter#184.

**Comment by tirexx** [comment]
Nice to hear this!
