### ISSUE TITLE
The dependency NUnit3TestAdapter 3.0.10 in project  does not support framework DNXCore,Version=v5.0

### ISSUE THREAD

**Issue by sam-wheat** [nunit/nunit-vs-adapter#109]
Very sorry if this has been addressed previously.  
I've seen this post https://github.com/nunit/nunit-vs-adapter/issues/102 which does not appear to resolve this issue.
I am getting this error after installing NUnit3TestAdapter
The dependency NUnit3TestAdapter 3.0.10 in project Blog.IntegrationTests does not support framework DNXCore,Version=v5.0
Project.json :
{
  "version": "1.0.0-*",
  "description": "Blog.IntegrationTests Class Library",
  "authors": [ "Sam" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "net451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  },
  "dependencies": {
    "Autofac": "4.0.0-rc1-177",
    "Blog.Core": "1.0.0-*",
    "Blog.Domain": "1.0.0-*",
    "Blog.Model": "1.0.0-*",
    "Blog.Services": "1.0.0-*",
    "NUnit": "3.2.1",
    "NUnit3TestAdapter": 
      "3.0.10"
  }
}

**Comment by CharliePoole** [comment]
The adapter does not yet support dnxcore. :-(

Issue #102 deals with a different issue - using the 2.0 adapter to run 3.x tests.

**Comment by rprouse** [comment]
I am going to close this issue as a duplicate. Microsoft has a new adapter interface for .NET Core. It is being implemented in a separate repository. https://github.com/nunit/dotnet-test-nunit
