### ISSUE TITLE
Improve descriptions of the adapter

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-adapter#111]
See issue nunit/nunit3-vs-adapter#174

We need a readme file in this repo.

We should also update the text in both the vsix and nuget packages as Rob suggests in the referenced issue.

**Comment by CharliePoole** [comment]
I forgot: we decided to change the adapter name to display as NUnit 2 Test Adapter. This will apply to both the vsix and nuget packages. For zips, the version is already part of the file name.

**Comment by OsirisTerje** [comment]
Closed as the code for the change is merged to master.
