### ISSUE TITLE
NUnit failed to load

### ISSUE THREAD

**Issue by neofenril** [nunit/nunit-vs-adapter#113]
Hi, i'm experiencing issues with the adapter. I've already checked the issue #84 which seems to have similarities with mine  but I cannot find any solutions.
Using VS 2012
Nunit 3
NUnit3.TestAdapter

I'm creating a simple sln with one test NUnit3, then install packages with NUGet, then run it.

I get an UnsuportedFrameworkException because the test want to run with both Adapter 2.0.0 and 3.0.10. Still, with the Adapter 3.0.10, the tests are running but i've got a Test Run Failed at the end.
So I've tested by installing the "TestAdapter including NUnit 2.6.4 Framework". Here at the compilation, everything is ok for the Adapter 2.0.0 but there the NUnit Adapter 3.0.10 failed to load my dll.

I hope it's ok to post this here

**Comment by rprouse** [comment]
@neofenril sorry, but we will need more information. It still isn't clear to me what your problem is or what you are running.

> with the Adapter 3.0.10, the tests are running but i've got a Test Run Failed at the end.

Can you tell us what the error is or what you are seeing in Visual Studio? Can you give us an example of the tests? Are you installing the adapter through NuGet or as a VSIX Extension?

**Comment by neofenril** [comment]
Ok sorry i'll try to explain it better
I'm creating a solution with a basic test that run well within the Test Explorer Inside Visual Stodio.
But I need to do it this way for my purpose :
`            

         var proc = new Process();
            proc.StartInfo.FileName = cmdPath;
            proc.StartInfo.Arguments = Args;
            // set up output redirection
            proc.StartInfo.RedirectStandardOutput = true;
            proc.StartInfo.RedirectStandardError = true;
            proc.EnableRaisingEvents = true;
            proc.StartInfo.CreateNoWindow = true;
            // see below for output handler
            proc.ErrorDataReceived += proc_DataReceived;
            proc.OutputDataReceived += proc_DataReceived;
            proc.StartInfo.UseShellExecute = false;
            proc.Start();`
And so I got this problem. I don't understant why it say that the Run Failed 
![testerror](https://cloud.githubusercontent.com/assets/6536092/15821405/e805a906-2bef-11e6-8286-7f8d9fc8293c.PNG)

So in order to resolve the Error, as I said I've downloaded the "TestAdapter including NUnit 2.6.4 Framework", but now i got an error with the testAdapter 3.0.0 as you can see  there :

![testerror2](https://cloud.githubusercontent.com/assets/6536092/15821509/8adf4bf0-2bf0-11e6-8227-bc3abc3f1a95.PNG)

Sorry I don't know how to explain it well without screenshots
I hope this can help you

**Comment by CharliePoole** [comment]
You appear to have both adapters installed. Is there a reason for that? Have you installed one or both adapters globally using the .vsix extension? Your test assembly can't be both NUnit 2.6.4 and NUnit 3 - it has to be one of them!

**Comment by neofenril** [comment]
Hi,
Well I feel sorry that i had to disturb you for such an error of mine, you were right @CharliePoole , I had both version installed (Tools->Extensions and updates), and I had only checked by a right click on my test and manage nuGetPackage where only the 3.0.0 appeared. 
However thank you for the explanations !
