### ISSUE TITLE
Test Explorer only shows first category

### ISSUE THREAD

**Issue by cjbush** [nunit/nunit-vs-adapter#115]
If I annotate a test method with:

[Test, Category("Foo"), Category("Bar")]

the Test Explorer window only shows the test under the Foo category. If I change the order and have Bar first, it only shows up under the Bar category. For reference, Microsoft's framework allows grouping into multiple categories. I'm using version 3.2.0 of the adapter and Visual Studio 2015 Enterprise.

**Comment by rprouse** [comment]
This is a known issue in VS 2105 Update 2 that will be fixed in update 3, see #108

**Comment by cjbush** [comment]
Sorry for the duplicate! Thanks
