### ISSUE TITLE
Exception NUnit.Core.UnsupportedFrameworkException

### ISSUE THREAD

**Issue by sankethkrishnappa** [nunit/nunit-vs-adapter#117]
I am using Nunit Adapter 3.2.0 and Nunit Core Framework 3.2.1 to build my selenium C# GUI automation project.

Case 1:

Running the solution in my local desktop work fine with no errors. Adapter is able to identify test methods and execute

Case 2:

Deploying this build in a dev CI server complies with no errors, but when the test fails to execute the referred test dll. Its throwing below exception..

Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in L:\Builds\xx\xxxxx\xxxxxAutomation_Nunit\bin\xxxxxAutomation_Nunit.dll

Done all analysis to solve, no luck. Hence posting for help.

**Comment by CharliePoole** [comment]
NUnit.Core.UnsupportedFrameworkException is an exception issued by NUnit V2 when finding either no test framework, or a framework other than NUnit V2.

Your CI machine is apparently using NUnit V2 rather than NUnit 3.
