### ISSUE TITLE
Async tests not fully supported

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-adapter#12]
When running async tests in visual studio the source is not visible when double clicking on the test. Also code coverage is not working for async tests. Also async tests take an extremely long time to run like 15+ seconds even though the execution time shows a very short time like 1ms.

See discussion at https://bugs.launchpad.net/nunit-vs-adapter/+bug/1221947

**Comment by CharliePoole** [comment]
@OsirisTerje This seems like one we would fix in both if confirmed.

**Comment by OsirisTerje** [comment]
I have tried to repro this, but it seems to work as it should.  The repro is here https://github.com/OsirisTerje/NUnit.Issues  under folder Issue12.
I'm closing this as norepro.

**Comment by CharliePoole** [comment]
It's pretty old, so not surprising. How do you want to handle the 3.0 part of these issues? Move to 3.0=Only for later checking? Check it out immediately and drop from any milestone?

**Comment by OsirisTerje** [comment]
This also works with NUnit3.  I have removed the milestone.
