### ISSUE TITLE
No tests found to run when TestFixture is a nested class

### ISSUE THREAD

**Issue by pitlyck** [nunit/nunit-vs-adapter#126]
Hi,

I am unable to run tests by selecting "Run Tests" from the context menu in VS2015 when the test fixture is a nested class.

Right-click in the window with code below, then select "Run Tests". In output window I can see output from tests: **No tests found to run.** 

Example:
```
public class NestedClasses
    {
        [TestFixture]
        public class NestedClass1
        {
            [Test]
            public void Test1()
            {
                Assert.Pass();
            }
        }
    }
```

I can see the test in list of tests in Test Explorer window and I am able to run it from there, but this is not what I want to do when I need to run/debug specific test/fixture that I am currently working on.

I am sure it worked before switching from NUnit 2.6.4 to NUnit 3.2.0.

I tried similar scenario with Microsoft VisualStudio UnitTesting framework and the test was run properly, so I expect this is nunit-vs-adapter issue.

VS 2015 Update 3 + NUnit3 Test Adapter v3.4.1 + NUnit 3.2.0

**Comment by rprouse** [comment]
Since this is an issue with the NUnit 3 adapter, I am moving this issue to that repository.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit3-vs-adapter #218](https://github.com/nunit/nunit3-vs-adapter/issues/218) via [**ZenHub**](https://www.zenhub.com/)
