### ISSUE TITLE
nunit Test Adapter Not Compatible with TFS 2015 Build and Release Manager

### ISSUE THREAD

**Issue by theMickster** [nunit/nunit-vs-adapter#128]
We've recently upgraded our nunit tests to 3.0 and are now seeing all test executions during the build and release process fail to execute. We are running **TFS 2015 Update 3** using the new Build and Release Manager products, and, specifically, the **Visual Studio Test** task to execute our tests. The task executes this tool  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe and is failing to find and execute any tests regardless of whether we point to the full path of the test adapter or the packages folder. See the attached series of tests not found messages. 

Any suggestions about what can be done to get these tests to run? 
![error](https://cloud.githubusercontent.com/assets/19419392/18437944/753e5c6e-78bc-11e6-9722-95185dbd6b60.png)

**Comment by CharliePoole** [comment]
I see from your console output that you are using the NUnit 3 Test Adapter rather than the NUnit Test Adapter, so I'm moving this issue there. Unfortunately, the names are a bit close and VS refers to both of them as the "NUnit Adapter".

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #229](https://github.com/nunit/nunit3-vs-adapter/issues/229) via [**ZenHub**](https://www.zenhub.com/)
