### ISSUE TITLE
[Suggestion] vs runner nuget package: do not modify project references

### ISSUE THREAD

**Issue by ig-sinicyn** [nunit/nunit-vs-adapter#129]
As it is for now, installation of NUnit3TestAdapter package adds references to the NUnit3.TestAdapter and Mono.Cecil.* assemblies. These should not be uncluded as lib artifacts, .targets file should be used instead.

[xUnit](https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.nuspec) as example.

**Comment by CharliePoole** [comment]
I'm working on a build that will put the extension in the tools directory, possibly in time for the 3.5 release. The original adapter (circa 2010) had to be in the lib directory and we never changed it.

**Comment by CharliePoole** [comment]
This essentially duplicates #127
