### ISSUE TITLE
Adapter fails to discover tests

### ISSUE THREAD

**Issue by brunoss** [nunit/nunit-vs-adapter#131]
The following messages appears on `output` Window after trying to rebuild my `Nunit` test project

```
------ Discover test started ------
NUnit Adapter 3.5.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
RemotingException: Found two different objects associated with the same URI, '/ad6409a5_eed6_4df5_b143_6aea6249e17e/TestAgency'.
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Found two different objects associated with the same URI, '/ad6409a5_eed6_4df5_b143_6aea6249e17e/TestAgency'.
========== Discover test finished: 0 found (0:00:00.4420455) ==========
```

Interestingly the last change that I made to my visual studio is that I put a product key on it. Before that the tests were able to be found.

This happened for me with Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Running as administrator

.Net Framework 4.5.2

NUnit version 3.5.0

I am using the visual studio extension test adapter 3.5.0

I already tried to reinstall the adapter after putting my product key.

The following message also appears at the very end of test discovery, if I rebuild my solution (which has tests with other testing frameworks)

`An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Format of the executable (.exe) or library (.dll) is invalid.`

**Comment by brunoss** [comment]
The test discovery was successful after I changed the test to prefer 64 bits

Test -> Test Settings -> Default processor architecture -> x64

**Comment by CharliePoole** [comment]
Since this is about the NUnit 3 adapter, I'm moving the issue to that project.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #248](https://github.com/nunit/nunit3-vs-adapter/issues/248) via [**ZenHub**](https://www.zenhub.com/)
