### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by j2ghz** [nunit/nunit-vs-adapter#137]
Is support planned?

**Comment by OsirisTerje** [comment]
Yes

**Comment by OsirisTerje** [comment]
I'll keep this as the issue for supporting VS2017.  We need to do the same here, converting it to support vsix3.

**Comment by OsirisTerje** [comment]
@rprouse already fixed this in #135 , so all we need to do is to release this.  I'll close this, since #135 handles the changes that are needed.

**Comment by CharliePoole** [comment]
@j2ghz FYI there will be a release but it's at the end of the queue after the framework, console and nunit 3 adapter releases so probably won't happen till the end of the month.

**Comment by j2ghz** [comment]
Thanks for the info. I compiled it from master myself, installed and it works well enough for my purposes.
