### ISSUE TITLE
Adapter requires test project pbd's to be generated for tests to be executed

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit-vs-adapter#144]
Same issue as we had on nunit3-adapter (https://github.com/nunit/nunit3-vs-adapter/issues/276) , and same fix is required.

**Comment by CharliePoole** [comment]
@Osirisrje In December you commented on nunit/nunit3-vs-adapter#276 that it was working correctly in NUnit 2. Did we change something in the release?

**Comment by OsirisTerje** [comment]
I referred to the 2.0 version of the adapter, not the master-branch which had the new Cecil stuff

**Comment by CharliePoole** [comment]
Ah... now I get it.

**Comment by OsirisTerje** [comment]
Fixed in release 2.1.1
