### ISSUE TITLE
Visual Studio 2017: Test Adapter 2.1.0 can't find tests in Test Explorer

### ISSUE THREAD

**Issue by Robert-INdotNET** [nunit/nunit-vs-adapter#146]
In Visual Studio 2017 with the latest NUnit Nuget Packages the discovering of new tests doesn't work.

You can try it yourself:
Make a new Solution and a test project in Visual Studio 2017. Then add the latest Nuget Packages:
- NUnit 3.6.1
- NUnitTestAdapter 2.1.0

Write a simple TestFixture class, build the project. The Test Explorer can't find any tests.

While reading the issues here, I found a workaround:
Downgrade from NUnit version 3.6.1 to version 2.6.4, rebuild -> Discovering of Tests successfully!

**Comment by OsirisTerje** [comment]
NUnit 3.* requires NUnit3TestAdapter .  See https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter 

So instead of downgrading NUnit, upgrade the adapter instead :-)

**Comment by Robert-INdotNET** [comment]
Thank you - it works! The Nuget top list was misleading.
