### ISSUE TITLE
When Debugging UI Tests, Visual Studio No Longer Breaks on Exception

### ISSUE THREAD

**Issue by DarthGregarious** [nunit/nunit-vs-adapter#150]
Visual Studio is no longer pausing execution while debugging NUnit/Coypu UI tests. In Debug Output, it is showing an InvalidOperationException and an IOException related to attempting to communicate over a pipe that has already been broken/terminated.

It used to break automatically on these exceptions and let you inspect the program. Now it seems to just crash when it encounters an unhandled exception.

I thought this issue might be related to #143 or just a misconfiguration on my end. But even after using the pre-release adapter provided in #143, this continues to be a problem. 

I added the class BreaksOnCoypuExceptionTest to the repro solution I provided in #143 that reproduces this problem.

[break-nunit-adapter.zip](https://github.com/nunit/nunit-vs-adapter/files/865312/break-nunit-adapter.zip)

**Comment by DarthGregarious** [comment]
![image](https://cloud.githubusercontent.com/assets/7608479/24256837/95360da6-0fbf-11e7-8e33-e8a506a0adf0.png)

When attempting to debug the CoypuExceptionTest (which only throws an exception), it simply exists prematurely and shows this output.

**Comment by OsirisTerje** [comment]
Does this also happens with the fixed adapter I enclosed on #143 ?

**Comment by DarthGregarious** [comment]
Yes.

**Comment by OsirisTerje** [comment]
Well, it works on my machine :-)
![image](https://cloud.githubusercontent.com/assets/203432/24267101/773f3904-1009-11e7-8271-b4a44045fc18.png)

Using this exception setting
![image](https://cloud.githubusercontent.com/assets/203432/24267115/8680aa6a-1009-11e7-952c-7c1c80962411.png)

**Comment by DarthGregarious** [comment]
Yes, that works... but I never had to do that before. And in my actual UI test it caused the execution to break at least 30 times before I had to add a specific exception for Microsoft.CSharp.RuntimeBinder.RuntimeBinderException. Only then did it finally make it to the MissingHtmlException.

Interestingly, immediately after that, it also paused on an exception I hadn't seen before: a "rethrown" MissingHtmlException wrapped in an NUnit.Core.NUnitException. I think that might be important.

I can approximate the old behavior by setting up my Exception Settings like this: 

![image](https://cloud.githubusercontent.com/assets/7608479/24268329/cbb4c556-0fe3-11e7-8764-4c5576864d26.png)

But it's not ideal. I have to inspect the .InnerException property to find the problem. And when it pauses, the call stack looks like this:

![image](https://cloud.githubusercontent.com/assets/7608479/24268357/e499c1de-0fe3-11e7-818b-6bcb5e2b7f4b.png)

Whereas the call stack used to show my code.

I'm not convinced that something didn't get broken here. It seems like the adapter maybe used to rethrow that NUnitCoreException.InnerException.

**Comment by DarthGregarious** [comment]
I downgraded to v2.0 of the VS Adapter and used the default exception settings and... it did not pause on the MissingHtmlException. I am going to have to do more investigation to figure out what changed here.

**Comment by OsirisTerje** [comment]
Ok, at least that makes sense.  When you're in there, please also check on the 2.0 adapter whether you get the exception wrapping the same way.

**Comment by OsirisTerje** [comment]
I'll close this for now.  If you find something here that really doesn't work, we can just reopen the issue.
