### ISSUE TITLE
Getting WorkerId fails in debug

### ISSUE THREAD

**Issue by botinko** [nunit/nunit-vs-adapter#166]
Hi! 

1, Visual Studio 2017 Version 15.5.2
2. NUnit test adapter V 3.9 
3, Nunit 3.9 (installed via nuget) 

When I try to debug test from Test Explorer, getting TestContext.CurrentContext.WorkerId throws null reference exception. 
When I debug test in Rider or via Resharper in VS, then all is ok.

**Comment by OsirisTerje** [comment]
Issue moved to [nunit/nunit #2696](https://github.com/nunit/nunit/issues/2696) via [**ZenHub**](https://www.zenhub.com/)
