### ISSUE TITLE
[SetUp] not being picked up

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-vs-adapter#168]
@pedrokarsan91 commented on [Wed Mar 28 2018](https://github.com/nunit/nunit/issues/2784)

I have installed NUnit 2 Test Adapter on Visual Studio 2017 Community Edition
I have NUnit v2.6.3 installed in the class library

When I run tests it does not reach [SetUp]

I have another project that has the exact same thing but works just fine.

---

@ChrisMaddock commented on [Wed Mar 28 2018](https://github.com/nunit/nunit/issues/2784#issuecomment-376803309)

Hi @pedrokarsan91 - the repository is for the NUnit 3 framework. I'll move your issue over to the NUnit 2 Test Adapter repo, for someone there to comment on.

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".

**Comment by pedrokarsan91** [comment]
@OsirisTerje I have found the issue. I had a partial class in a different folder but did not have the same namespace. Works as expected now.

Thank you :)
