### ISSUE TITLE
Support for disable app domain

### ISSUE THREAD

**Issue by ptrupti** [nunit/nunit-vs-adapter#171]
Hi,
We need to run our tests in the default app domain because we are using CEFSharp in our application which needs to run in default app domain. Any pointers on how to disable the app domain creation or even modifying the existing vs adapter code would be appreciated.
Thanks
Trupti

**Comment by jnm2** [comment]
Here is the PR which added this support in the current adapter: https://github.com/nunit/nunit3-vs-adapter/pull/391.

**Comment by OsirisTerje** [comment]
And the setting for the DomainUsage in runsettings is shown here: https://github.com/nunit/docs/wiki/Tips-And-Tricks 

![image](https://user-images.githubusercontent.com/203432/41764758-66ca3190-7602-11e8-9ba1-59c0135ae9e9.png)

**Comment by z002Holpp** [comment]
Hi,
same here. Need to run multiple assemblies without switching the app domain for each assembly. Having all test assemblies run in the same default app domain would be a great solution for us.

Any hints how to achieve that or what would be the best way to modify the existing adapter are highly appreciated.

Thanks,
Stefan
