### ISSUE TITLE
NUnitTestAdapter 2.1.1 not working with Visual Studio 2017 15.8.0

### ISSUE THREAD

**Issue by gtrubach** [nunit/nunit-vs-adapter#174]
Hello!

VS 2017 recently got an [update](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes) to 15.8.0 version. After I updated my VS to the latest version and updated test adapter to the version 2.1.1 (NuGet) VS is able to discover tests but cannot run it:

> [8/17/2018 9:27:00 AM Informational] ------ Run test started ------
> [8/17/2018 9:27:00 AM Informational] ========== Run test finished: 0 run (0:00:00.3633409) ==========

To check this problem I downloaded this repo and opened NUnitTestDemo solution. I installed the latest adapter 2.1.1 through NuGet and see that tests are not able to run.

Also I found out that if I copy adapter libraries (from NUnitTestAdapter.2.1.1\tools folder) to bin/Debug folder test become able to run.

Can you help with this problem?

**Comment by OsirisTerje** [comment]
I'll have a look

**Comment by OsirisTerje** [comment]
Can you add the adapter nuget package to all test projects?
That should make it work.
Optionally check if turning off the Active solution options below helps:
![bilde](https://user-images.githubusercontent.com/203432/44254856-5e45c600-a204-11e8-8ff8-87aac2308136.png)

**Comment by OsirisTerje** [comment]
I can repro this issue, and it is solved by turning off the Active Solution checks above. 
*With the Active Solution boxes checked:*
![bilde](https://user-images.githubusercontent.com/203432/44260247-1a5abd00-a214-11e8-9f09-c93c85959212.png)

*With the Active Solution boxes unchecked:*
![bilde](https://user-images.githubusercontent.com/203432/44260269-2e9eba00-a214-11e8-94b5-91ce09987e53.png)

**Comment by gtrubach** [comment]
@OsirisTerje Thanks for your work! I will check if this option works for me on Monday.

**Comment by Shyam-Gupta** [comment]
@OsirisTerje The second option: **'For compatibility, fallback to global VSIX adapter for MSTest v1 and NUnit test projects that don’t reference a test adapter',** comes into effect only for VSIX test adapters. Since in this case, nuget adapter is being used, this option will not help.

@gtrubach I have verified that as a workaround unchecking both the options does work.
However, in my opinion, a better solution would be to move to latest NUnit3TestAdapter which does not have this problem and also offers a bunch of perf improvements.

**Comment by gtrubach** [comment]
@OsirisTerje Solution with unchecked Active Solution boxes works. Thanks!

@Shyam-Gupta I'm working on project that uses NUnit 2 so I have to use NUnitTestAdapter for them. There is no possibility to move to NUnit 3 now.

**Comment by kestasjas** [comment]
Unchecked **Active Solutions** works with NUAdapter-2.0.0 & NUnit-2.6.4.
Not working with NUAdapter-2.1.1 & NUnit-3.10.1

**Comment by OsirisTerje** [comment]
@kestasjas NUAdapter2 *only* works with NUnit2.  NUnitAdapter3 *only* works with NUnit3.

**Comment by kestasjas** [comment]
Clear! Somehow was not able to find NUAdapter-3. ?!

**Comment by bgavrilMS** [comment]
I have the same problem, but I am using VS 15.9.0 Preview 5 and the workaround does not seem to work. I captured the diagnostic logs  
[log.txt](https://github.com/nunit/nunit-vs-adapter/files/2576224/log.txt)

The project used is a minimal test with Nunit2: 
https://github.com/bgavrilMS/NUnitTestProject1/blob/e804748ca9f7aae96b2b64f603fbc0e0e0adf47f/NUnitTestProject1/UnitTest1.cs

**Comment by OsirisTerje** [comment]
@bgavrilMS  What kind of appcenter app are you working on?   It doesn't make sense that a Microsoft product should use NUnit 2.  

We'll anyway need to fix this issue.

**Comment by bgavrilMS** [comment]
@OsirisTerje - apologies, I meant Xamarin UITests have a hard dependency on NUnit 2, we just run our Xamarin tests in AppCenter. 

See https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/, it clearly states

" Note - Xamarin.UITest requires NUnit 2.6.3 or 2.6.4 to run tests. Xamarin.UITest is not compatible with NUnit 3.x."

**Comment by sdelval** [comment]
> Are you using VSIX or nuget adapters?
> Can you add the adapter nuget package to all test projects? [Update: No, this doesnt help, see below.]
> That should make it work.
> Optionally check if turning off the Active solution options below helps:
> ![bilde](https://user-images.githubusercontent.com/203432/44254856-5e45c600-a204-11e8-8ff8-87aac2308136.png)
> 
> This can be related to what I discuss here: http://hermit.no/vsix-based-test-adapters-to-be-deprecated-in-visual-studio-for-c-and-visual-basic-to-speed-up-testing/
> 
> [Update]
> I checked and see that the 2.X adapter doesn't copy its dll to the output, as the 3.X adapter do. We might need to fix that. But turning off the options above should make things work back to normal. The secondary option there is meant to make this work anyway, but it might not work as intended. This the behaviour you see is a breaking change in 15.8, but the second option above _should_ keep it non-breaking......

Regarding your screenshot, I would recommend to keep "Additionally discover tests from built assemblies..." box checked. Indeed I've experienced some missing tests in my run for second platform (Platform.iOS) after rebuilding solution because this option was unchecked.

**Comment by OsirisTerje** [comment]
Thanks @sdelval  !  Good advice!

**Comment by joaorosado** [comment]
I was changing my nuget packages to use PackageReferences instead of the package.config files and even the workaround suddenly stopped working.
I guess that with the new nuget system it really needs the adapter files on the output directory since It started working as soon as I manually copied them to the folder.

Trying to workaround it but it's not easy due to having a different version of mono.cecil on my project :/

**Comment by chari-sampathkumar-axway** [comment]
I use VS 2017 pro version 15.9.2 and nunit3testadapter 3.10.0. I can repro the issue and the work around solves the problem. But the settings changes get's saved into .suo file which goes away when we do "git clean". Is there a way out of it that enables us not to touch .suo files?

**Comment by rprouse** [comment]
The setting mentions that you can add the setting to the runsettings file, although I'm not sure how that is done. Google? 😄

**Comment by chari-sampathkumar-axway** [comment]
@rprouse not much info on google. 

If anyone watching the issue, if they can let us know how to control that setting via runsettings instead of losing it via .suo, that will be helpful.

**Comment by joaorosado** [comment]
You probably should open a issue on nunit3-vs-adapter repository instead
since they have a diferent code base.

You should not be having this problem with it as long as your project has
both adapter and nunit framework included via nugets.

Answering your question, as far my tests gone the settings like you noticed
are stored in the .suo.
The path for the runsettings file is also stored there ...so also not an
option.

Back to this topic.

As workaround for this problem in my case was to replicate the fix they
have on the nunit3-vs-adapter into one of my test projects csproj (with the
assemblies changed to match the ones for this adapter version):

https://github.com/nunit/nunit3-vs-adapter/blob/master/nuget/net35/NUnit3TestAdapter.props

With that and both adapter and framework comming from nugets everything
works fine without changing the settings.

**Comment by chari-sampathkumar-axway** [comment]
@joaorosado thanks for the reply.  I do pull both the adapter (3.10.0 - little behind than the latest) and nunit  framework (3.10.1) from nuget and the problem still remains. It might be possible that with the latest versions of both the problem may be solved. I will give it a shot and confirm.

**Comment by chaami** [comment]
Hi,
It seems that the test adapter is going to work even less with the upcoming 16.0 version (16.0.0 Preview 3.0).
Tested configuration: NUnit 2.6.4 with NUnitTestAdapter 2.1.1
From what I can tell:
- The workaround allows the NUnit VS Adapter to be called.
  It seems equivalent to copying the dlls to the test bin directory as the nunit3-vs-adapter fix does.
- The way the test adapter must have been changed: I now get a warning indicating that the passed testcase does not match any test.
Launching the tests with the nunit3-console works fine (with the NUnit2FrameworkDriver).
Is there any lead to fix this issue and/or even get rid of the workaround ?
I have no idea on how things work, but I am ready to give a hand if possible...
Kind regards.

**Comment by OsirisTerje** [comment]
@chaami I'll have a look, awesome if you can help out.

**Comment by chari-sampathkumar-axway** [comment]
@chaami @OsirisTerje  FYI: With VS 2017, if you use PackageReference, everything seem to be working fine without having to modify any visual studio settings. I'm not sure how it will impact with upcoming version though. Worth a try.

**Comment by GideonZhao** [comment]
Turning off the Active Solution works for me. VS 2019, NUnit 2 Test Adapter 2.1.1

**Comment by chrisogonas** [comment]
> off the Active Solution

How do you turn off the Active Solution ?

**Comment by OsirisTerje** [comment]
Please update to the newest adapter version, https://www.nuget.org/packages/NUnitTestAdapter/, or https://github.com/nunit/nunit-vs-adapter/releases/tag/V2.2  ,  see release notes:  https://github.com/nunit/docs/wiki/AdapterV2-Release-Notes
