### ISSUE TITLE
Should the VSIX ever support VS 2019?

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-vs-adapter#177]
It would be good to document this clearly before folks start asking.

**Comment by rprouse** [comment]
See discussion in nunit/nunit3-vs-adapter#576

**Comment by OsirisTerje** [comment]
Repeated here:
If you look at what we say on the VS marketplace, it is clearly stated there, I think.
It will be deprecated:
"NOTE: - EARLY WARNING: Please observe that VSIX test adapters will be deprecated in the upcoming Visual Studio 2019. Please add the nuget adapter package to your solutions instead. See further information here and here"

I added this statement this summer when it was clear.

**Comment by OsirisTerje** [comment]
The 2.2 version supports VSIX for VS 2019, so I am closing this.
