### ISSUE TITLE
Update NUnit library to 2.7.1

### ISSUE THREAD

**Issue by christianbumann** [nunit/nunit-vs-adapter#184]
It would be nice to update NUnit library to 2.7.1.

And also nicer to have a release :-) The first point we could do for you

**Comment by christianbumann** [comment]
Libraries [here](https://github.com/nunit/nunit-vs-adapter/tree/master/lib) must be updated to the version 2.7.1 of NUnit.

**Comment by OsirisTerje** [comment]
@christianbumann  Released a beta version, see https://www.nuget.org/packages/NUnitTestAdapter/2.3.0-beta01
