### ISSUE TITLE
How to change used nunit 2 version of test adapter to e.g. v2.7.1 ?

### ISSUE THREAD

**Issue by informatorius** [nunit/nunit-vs-adapter#186]
How can I change the nunit 2 version of test adapter to e.g. v2.7.1 ?

**Comment by christianbumann** [comment]
Libraries [here](https://github.com/nunit/nunit-vs-adapter/tree/master/lib) must be updated to the version 2.7.1 of NUnit.

**Comment by OsirisTerje** [comment]
@informatorius   Released a beta version, see https://www.nuget.org/packages/NUnitTestAdapter/2.3.0-beta01
