### ISSUE TITLE
Syntax for auto-removable test suffix

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit-vs-adapter#192]
For example:
```
[Test]
public void Test_Serialize() {
}
[Test]
public void Test_Serialize__ArgumentNullException() {
}
```
Here I'd like NUnit to remove everything starting with `__` (double underscore). And Test Explorer to show those methods as one node with children.

I have already opened this issue https://github.com/nunit/nunit/issues/3579 but it looks like here is better place.

**Comment by mikkelbu** [comment]
@Denis535 This is the project for the NUnit 2 adapter. I moved your issue to nunit/nunit3-vs-adapter#760. Is your request for NUnit 2 or 3?

**Comment by Denis535** [comment]
Of course NUnit 3.

**Comment by mikkelbu** [comment]
Ok. Then I'll close this issue :)
