### ISSUE TITLE
Any plans to release this adapter for Visual Studio 2022?

### ISSUE THREAD

**Issue by albx** [nunit/nunit-vs-adapter#196]
It could be useful having this adapter available for Visual Studio 2022. Is this planned?
Thank you

**Comment by rprouse** [comment]
We don't have plans to release the extension for VS 2022. I'd recommend that if you are still using NUnit 2 that you switch your projects to use the `NUnitTestAdapter` NuGet package. Adding test adapters to Visual Studio as extensions is deprecated so we are only supporting NuGet packages now.

To me, using NuGet is a huge win as it is automatically available for all developers of your code without any special setup. It also gets pulled in and is usable from your CI/CD pipelines.

**Comment by albx** [comment]
@rprouse thanks for the answer. We're planning exactly what you suggested. So this issue can be closed :) 
Thanks again!
