### ISSUE TITLE
Uncaught System.Security.SecurityException causes test discovery to fail

### ISSUE THREAD

**Issue by venison** [nunit/nunit-vs-adapter#33]
We have a project that has some dll's from the Unity Game engine that cause this exception during the test discovery.  We don't really care about trying to test anything from that dll, but the problem is it is blocking test discovery for our Nunit based unit tests that have no references to anything in the problematic dll.

Could we catch this exception, I believe in the NUnitTestDiscoverer, which already seems to handle other types of exceptions?  Please let me know if there is any information I can provide that can help this along.

As an addendum, we did try to pull down the code and build/add the try/catch ourselves, however we failed spectacularly at simply trying to build the project with VS 2010, 2012, and 2013.  We had to comment out a number of lines of code to get it to build and broke much in the process.

**Comment by OsirisTerje** [comment]
No further information or response.

**Comment by Kavignon** [comment]
I have the same issue but with the MS framework for unit testing.
There is no source code available when I'm trying to access a game object I created in VS15 using the MonoBehaviour class.
The calls to the Unity Engine are internal, but I'm trying to look for a workaround in order for it to work !
