### ISSUE TITLE
Create initial version of adapter that uses NUnit 3.0

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-adapter#41]
This will be a first, rough cut of running NUnit tests from an adapter that supports 3.0.

Only 3.0 will be supported, pre-3.0 tests will be ignored.
The adapter name will be different from the existing adapter, allowing both to be installed.

**Comment by jmecosta** [comment]
i can gladly test this once its available. so far the current adapter misses some of the OneTimeSetUpAttribute

**Comment by CharliePoole** [comment]
Note that it's an error that the adapter even tries to run tests built against NUnit 2.x. I thought that we had put out an update that gave a proper error message. @OsirisTerje ?

**Comment by OsirisTerje** [comment]
No, I had that in a branch for 2.6.3, but we decided to wait for 2.6.4 which threw an exception in that case, and that code has not been done after that.  We should perhaps  do this now, together with the updates needed for VS 2015.  I have an issue with the nuget adapter and CTP6, which seems to be a bug in the CTP6, and would like that to be resolved first.  It would be nice to drop out a 1.4 with both these things resolved, and with a few bugs fixed too.

**Comment by CharliePoole** [comment]
I agree. It would stop a certain amount of confusion folks have over this.

**Comment by jmecosta** [comment]
is there any way of me hacking v 1.2.0.1 to trigger also calls on OneTimeTearDown and OneTimeSetUp? a quick and dirty way for me is fine, at least until final version is released.  Nice to hear CTP6  has been release, really hope they fix one of my bugs

**Comment by CharliePoole** [comment]
No, because the adapter has nothing to do with this issue - it's the NUnit core used by the adapter that actually recognizes and runs tests. When @OsirisTerje releases an adapter that uses NUnit 2.6.4, you'll get an error message if you try to run NUnit 2.x tests. This is an _improvement_ over the current adapter because the execution is entirely unpredictable and unreliable. It only works at all by accident, because many of the attributes have the same name.

NUnit 3.0 does not recognize attributes by name at all, but by their Type identity.

**Comment by jmecosta** [comment]
ok thanks... do you have any idea when this can be ready... by the way if trying to update this to use 3.0 myself is this going to be a hell of a work or not...

**Comment by CharliePoole** [comment]
To do it yourself, you would need to remove all references to NUnit assemblies from the adapter, become familiar with the new framework API or the engine API, choose whether to go through the engine or deal directly with the framework, identify all the places where the adapter previously called into NUnit and replace it with calls to one of the APIs, identify where info is passed back to VS and create classes to translate the 3.0 results and events to what VS expects. Definitely not the easiest place to start with NUnit development. :-)

Otherwise, you should track progress on #41

**Comment by CharliePoole** [comment]
There is now a separate project for the NUnit3TestAdapter, so I'm closing this as a duplicate.
