### ISSUE TITLE
ItemGroup added to project files.

### ISSUE THREAD

**Issue by Vkoslak** [nunit/nunit-vs-adapter#51]
Software verions:  Visual Studio 2013, Windows 7 Ultimate, Nunit Test Adapter ver 1.2.0.0

**Steps to reproduce:**
- Start Visual Studio and open a solution with a unit test project written for NUnit.
- Find a unit test and right click on it selecting "run selected unit tests" from the context menu.
- Unit test is executed.

**Expected Results:**
- Nothing extra is added to the project definition.

**Actual Results:**
- The following has been added to all nunit projects,
```xml
 <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
```

-----------------------------------------
I need to play nice with others. My use of this tool shouldn't pollute my project files.

**Comment by OsirisTerje** [comment]
I'll close this as we have no way to do anything with this.  The new testgenerator will create Unit Test projects, and when we do "Create an NUnit VS Template #300, that is probably the best we can do.
