### ISSUE TITLE
VS 2015

### ISSUE THREAD

**Issue by siegfriedpammer** [nunit/nunit-vs-adapter#58]
When will there be a release for VS 2015? I tried building a package myself, but I failed because I don't have VS 2012 at my disposal. Thank you very much!

**Comment by OsirisTerje** [comment]
The nuget adapter works for VS 2015.  You can also download a pre-release version from https://bintray.com/nunit/NUnitAdapter/NUnitAdapter/1.2.0.1/view 

Also see my blog post here about VS 2015 and NUnit:  http://geekswithblogs.net/terje/archive/2014/11/14/visual-studio-2015-and-nunit-with-a-little-nuget-issue.aspx

**Comment by ehartford** [comment]
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'NUnit Test Adapter' requires a version of the .NET Framework that is not installed.

**Comment by OsirisTerje** [comment]
It should be enough with 4.5, the one that comes with Visual Studio.  Which version of VS do you install it into ?  And which version of the adapter do you use ?

**Comment by PaulAchess** [comment]
Hi, I'm experiencing this issue, was there any fix ?
My log is here (sorry, I couldn't just attach it)


06/03/2015 17:05:52 - Microsoft VSIX Installer
06/03/2015 17:05:52 - -------------------------------------------
06/03/2015 17:05:52 - Initializing Install...
06/03/2015 17:05:52 - Extension Details...
06/03/2015 17:05:52 - 	Identifier      : NUnitTestAdapterInstall..7c53286e-ac4f-485f-915c-5ec5a4c47b0c
06/03/2015 17:05:52 - 	Name            : NUnit Test Adapter
06/03/2015 17:05:52 - 	Author          : Charlie Poole
06/03/2015 17:05:52 - 	Version         : 1.2.0.1
06/03/2015 17:05:52 - 	Description     : NUnit adapter for integrated test execution under Visual Studio 2012 (all updates), Visual Studio 2013 (all updates), and the Visual Studio 2015 Preview and CTPs. Compatible with NUnit 2.0 through 2.6.3.
06/03/2015 17:05:52 - 	Locale          : en-US
06/03/2015 17:05:52 - 	MoreInfoURL     : http://nunit.org/index.php?p=vsTestAdapter&r=2.6.3
06/03/2015 17:05:52 - 	InstalledByMSI  : False
06/03/2015 17:05:52 - 	SupportedFrameworkVersionRange : [4.5]
06/03/2015 17:05:52 - 
06/03/2015 17:05:52 - 	Supported Products : 
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Ultimate
06/03/2015 17:05:52 - 			Version : [11.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Ultimate
06/03/2015 17:05:52 - 			Version : [12.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Ultimate
06/03/2015 17:05:52 - 			Version : [14.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Premium
06/03/2015 17:05:52 - 			Version : [11.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Premium
06/03/2015 17:05:52 - 			Version : [12.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Premium
06/03/2015 17:05:52 - 			Version : [14.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Pro
06/03/2015 17:05:52 - 			Version : [11.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Pro
06/03/2015 17:05:52 - 			Version : [12.0]
06/03/2015 17:05:52 - 		Microsoft.VisualStudio.Pro
06/03/2015 17:05:52 - 			Version : [14.0]
06/03/2015 17:05:52 - 
06/03/2015 17:05:52 - 	References      : 
06/03/2015 17:05:52 - 
06/03/2015 17:05:52 - Searching for applicable products...
06/03/2015 17:05:52 - Found installed product - Microsoft Visual Studio Professional 2013
06/03/2015 17:05:53 - The extension with ID 'NUnitTestAdapterInstall..7c53286e-ac4f-485f-915c-5ec5a4c47b0c' is not installed to Microsoft Visual Studio Professional 2013.
06/03/2015 17:05:53 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
06/03/2015 17:05:53 - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
06/03/2015 17:05:55 - The extension with ID 'NUnitTestAdapterInstall..7c53286e-ac4f-485f-915c-5ec5a4c47b0c' is not installed to Microsoft Visual Studio Ultimate 2015 CTP.
06/03/2015 17:05:55 - Found installed product - Microsoft Visual Studio Premium 2015 CTP
06/03/2015 17:05:55 - Found installed product - Microsoft Visual Studio Professional 2015 CTP
06/03/2015 17:05:55 - Found installed product - Microsoft Visual Studio Community 2015 CTP
06/03/2015 17:05:55 - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
06/03/2015 17:05:55 - Found installed product - Global Location
06/03/2015 17:05:58 - The following target products have been selected...
06/03/2015 17:05:58 - 	Microsoft Visual Studio Ultimate 2015 CTP
06/03/2015 17:05:58 - 
06/03/2015 17:05:58 - Beginning to install extension to Microsoft Visual Studio Ultimate 2015 CTP...
06/03/2015 17:05:58 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'NUnit Test Adapter' requires a version of the .NET Framework that is not installed.
   à Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

**Comment by ehartford** [comment]
It's because you have visual studio 2015 preview installed.  You need to edit the .vsix and set the. Net dependency to MinVersion instead of Version

**Comment by PaulAchess** [comment]
Thanks, I just removed MaxVersion and that did the trick.
