### ISSUE TITLE
Adapter can't detect tests in VS 2013 Express U4

### ISSUE THREAD

**Issue by anilanar** [nunit/nunit-vs-adapter#59]
As the title says, adapter can't detect NUnit tests in VS 2013 Express Update 4 (using Nuget package, obviously).

**Comment by rprouse** [comment]
Did this work in previous versions of Visual Studio Express? I didn't think Express supports extensions. Even though the adapter is also packaged as a NuGet package, it is an extension.

**Comment by anilanar** [comment]
I have no idea, it's my first time using Express. I saw some posts in stackoverflow.com claiming that Nuget package works with Express and I assumed so. I know it doesn't support 3rd party extensions but I thought maybe the Nuget package used some other method to get around it.

**Comment by CharliePoole** [comment]
NuGet packages in general may work with Express, but the use of NuGet to
install an extension (vsix) is subject to the usual rules about extensions
AFAIK.

**Comment by rprouse** [comment]
The extension does work in the new free Community Edition of Visual Studio. There isn't much reason to use Express anymore, so I would suggest switching.

**Comment by OsirisTerje** [comment]
yes, use the community edition, see http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx.

**Comment by CharliePoole** [comment]
@OsirisTerje We should probably document somewhere that Express isn't supported.

**Comment by OsirisTerje** [comment]
Agree, I have updated the info on https://www.nuget.org/packages/NUnitTestAdapter/1.2.0 and https://www.nuget.org/packages/NUnitTestAdapter.WithFramework/1.2.0
