### ISSUE TITLE
NUnit VS Test adapter broken in Visual Studio 2013 Update 4

### ISSUE THREAD

**Issue by corliss** [nunit/nunit-vs-adapter#68]
Hi Guys, this seems related to #59, but is for standard Visual Studio 2013 + Update 4, not just Express.

I upgraded from Update 2 to Update 4 and now the adapter is totally unusable. 

The first time a solution is built and loaded, it discovers all tests. However, actually trying to run the tests does not work - it consistently displays "No tests to run". 

Rebuilding also does not work - now even the previously discovered tests disappear, leaving the test window empty. 

I'm surprised that others haven't run into these issues. Can you suggest any workarounds/diagnostics?

I'm running 1.2 of the adapter, on Windows 8.1 64-bit.

Cheers.

p.s. I do see this in the Test log:
```NUnit 1.2.0.0 discovering test is finished
Operation failed. The index entry of length 906 bytes for the index 'Idx_Stale_StateValue_DisplayName' exceeds the maximum length of 900 bytes.```

**Comment by OsirisTerje** [comment]
I do believe you might have quite long test names.  NUnit should not always generate long names, AND the VS Test Explorer don't like long names. 
To work around these, take a look at these https://github.com/nunit/nunit-vs-adapter/issues/3, and this https://bugs.launchpad.net/nunit-vs-adapter/+bug/1221780 to see if they can help you out.

**Comment by rprouse** [comment]
Version 2.0 of the adapter was just released, you should update and test with that. Also, are you using the NuGet package or the VSIX extension? I am using version 2.0 of the adapter installed as a VSIX in Visual Studio 2013 Professional Update 4.

**Comment by corliss** [comment]
Thanks for the quick response folks. Uninstalling 1.2 and installing the 2.0 VSIX works well; I'm back to the previous functionality as far as I can tell. Thanks again.
