### ISSUE TITLE
System.ArgumentException while running a test from VS

### ISSUE THREAD

**Issue by deepaksharma507** [nunit/nunit-vs-adapter#70]
Hi all,

I am using VS2012 with NUnit (V.2.0).
I am facing this strange issue while running my test from within VS. My test works fine when I run it from NUnit GUI, but fails when I run it from within the VS (Test Explorer) window. It throws the following exception.

Message returned System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Invalid token for impersonation - it cannot be duplicated.
   at System.Security.Principal.WindowsIdentity.CreateFromToken(IntPtr userToken)
   at System.Security.Principal.WindowsIdentity..ctor(SerializationInfo info)
   at System.Security.Principal.WindowsIdentity..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
 
Strangely enough, when I run the same test from Resharper Unit Test Explorer window it works fine again. It is driving me mad.
I am pretty sure this has something to do with NUnit being running under different identity, but how can I change it. 
Any advice !!

Thanks,
DS

**Comment by OsirisTerje** [comment]
Not an adapter issue.
