### ISSUE TITLE
Null Reference Exception on startup

### ISSUE THREAD

**Issue by immeraufdemhund** [nunit/nunit-vs-adapter#73]
Using Visual Studio 2015 Enterprise and test adapter 2.0.0.0 I frequently (seems consistently like every other time) get a NullReferenceException. The following is the entry from my activity log. 

> TestWindowPackage.Initialize failed with exception: 
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.VisualStudio.TestWindow.VsHost.TestWindowPackage.Initialize() 
> 
> PackageContainer loaded: False 

When this problem happens I am unable to open the test window and run any tests. Usually closing Visual Studio and re-opening it will resolve this.
I also think I remember getting this exception when using the new beta test adapter, but don't remember exactly. I do, however, remember getting this problem in previous versions of VS15 (for sure RC, CTP6, and CTP4)

**Comment by OsirisTerje** [comment]
Yes, the 3.0 beta adapter had some issues here, but the 2.6.4 is different and should not have them.  So this looks VS 2015 specific.  I have sent it further to MS for evalution.  Btw, you havent seen the same With MSTest ?

**Comment by immeraufdemhund** [comment]
And admit to using MSTests?!?!?! NEVER!

the answer is no, I have not seen this with MSTest, but I only have 1 very small project that uses MSTest for when I do codereviews on stack exchange.

 I'm also suspecting that it *might* be because of opening Visual Studio through MinGW. I created a function that searches the current directory for all .sln files and returns the first one as a variable called file. the function then opens which ever version of Visual studio I specify passing relative path of the solution file name. I just now switched it to be the absolute path and so far haven't had any problems. I don't recall seeing this problem when I open a solution via the "recently opened solutions" menu, but plan on tracking it now for a little bit.

**Comment by OsirisTerje** [comment]
Lol !

Ok, great that you keep a watch for a while. If nothing more pops up within a few days, I suggest you close the issue.

**Comment by immeraufdemhund** [comment]
Just crashed again. I am submitting a report with MS with a dump. I'll report back their findings as well.

**Comment by immeraufdemhund** [comment]
I'm not sure this will help or not, but here is to hoping. As I told you I was going to log how I open VS. So far it's 50/50 between using bash and right clicking failures. I started poking around and found that by deleting the MEF cache (%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache) that all was good with the world again. Next time it happens I would like to attach said 4 files and see if it replicates on your machine. Here is to hoping :8ball:
