### ISSUE TITLE
Unable to run TestCaseSource tests when the type under test uses Guid.ToString in a ToString override

### ISSUE THREAD

**Issue by ScottShingler** [nunit/nunit-vs-adapter#75]
First, let me present the test setup in F# (using FsUnit on top of NUnit):

    type SimpleRecord = { A: int; B: int } 
                        override x.ToString() = x.A.ToString()
    
    [<TestFixture>]
    type ``Simple Test Cases``() =     
        static member SimpleDataSource =
            [|
                [|{ A = 1; B = 2} ,3|]
            |]
    
        [<TestCaseSource("SimpleDataSource")>]
        member x.``SimpleTest`` (testData: SimpleRecord * int) =
            let data, expected = testData
            data.A + data.B
            |> should equal expected

This test will run and pass as expected.  However, changing the `ToString` override on SimpleRecord to include a call to `Guid.ToString()` will prevent the test from being run:

    type SimpleRecord = { A: int; B: int } 
                        override x.ToString() = x.A.ToString() + Guid.NewGuid().ToString()

With the above change, the test still appears in Test Explorer, but it will not be run.  Even right-clicking on it and selecting Run Selected Tests will not execute the test.  No errors are reported.

I also experimented with using `DateTime.ToString()` instead of `Guid.ToString()`, but that also refuses to run:

    type SimpleRecord = { A: int; B: int } 
                        override x.ToString() = x.A.ToString() + DateTime.Now.ToString()

As it turns out, if the tests are invoked from nunit-console.exe, they will actually run as expected.  This seems to be a bug with the NUnit Test Adapter for Visual Studio.

**Comment by OsirisTerje** [comment]
I am no F# guy and I just struggle with compiling this.  Could you upload a repro project somewhere  which compiles ?  That would be really helpful in tracking this down.

**Comment by ScottShingler** [comment]
@OsirisTerje I've created a repro project at https://github.com/ScottShingler/NUnitVSAdapter.Repro75

**Comment by CharliePoole** [comment]
Actually, this is a well-known issue in disguise. :-)

When tests are run using the NUnit console or gui runners, they are first loaded (discovered) and then executed. When running under the adapter, the tests are loaded twice, once in the discovery phase and again at the beginning of the execution phase. This is a result of the way the VS Test Window works: discovery and execution are run in separate processes created by VS.

This doesn't cause a problem in most cases. The tests are loaded twice, which means the code for creating any test data is run twice. Usually, the same data is generated both times.

However, when using random data, it's known that different data will be generated in each phase. Tests that are shown in the initial discovery seem to disappear while "unknown" tests are run.

In your case, the guid is generated twice. The first one is used as part of the name of the test, consequently, that test disappears in the execution phase. As a workaround, use the TestName property to actually assign a name to the test. I believe that should make it work although I haven't actually tried it.

**Comment by ScottShingler** [comment]
@CharliePoole You nailed it!

I've updated my repro project with a working example of the solution.

**Comment by CharliePoole** [comment]
Marked this as a duplicate of #15, which remains open.

The difference in the two is that we random test generation is native to NUnit, while the guid generation is in your test. We may be able to fix #15, but not this one.
