### ISSUE TITLE
Nuget version install script doesn't work withVS 2015

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit-vs-adapter#78]
The #77 issue had a comment on this, and it proves there is an issue in Nuget https://github.com/NuGet/Home/issues/1245 that causes the adapter dll's to not be set to Copy Local = false.  This means the adapter dll's will be present in the projects output, not what one would want to happen.  They do no harm, but it can be confusing and it is not needed.  
The install.ps1 script can be changed to avoid this issue.

**Comment by CharliePoole** [comment]
Why a new issue? Seems like this just duplicates #77.

**Comment by OsirisTerje** [comment]
Issue 77 is about Mono, and there is afaik no powershell support on Linux/Mono, so that issue must be resolved differently.  This issue is about the comment at the bottom of #77 which is different and have a different resolution

**Comment by CharliePoole** [comment]
True. However, the 2015 install caused the problem and there doesn't seem to be anything else we can actually fix on #77. I'll confirm that's the case and close it.

**Comment by OsirisTerje** [comment]
This is now the default behaviour, the dll's should be in the output, so closing this.
