### ISSUE TITLE
Adapter double runs tests in VS2015 with nuget version and VSIX version both installed

### ISSUE THREAD

**Issue by pessimism** [nunit/nunit-vs-adapter#79]
Given a VS2013 solution with the VSIX version installed and one copy of the nuget version in the solution, right clicking a test in test explorer and debugging launches the test one time

Given the same solution in VS2015 with the same VSIX version installed and same one copy of the nuget version in the solution, right clicking a test in test explorer and debugging launches the test twice.

Removing the VSIX version from VS2015 makes the tests run one time.  Ideally both the nuget and VSIX versions can coexist on a system and run tests only once, like they do in VS2013.

**Comment by CharliePoole** [comment]
We can try to confirm this but if it's confirmed it sounds like a VS2015 issue. If VS calls the adapter twice, then it will do it's job twice. :-)

For information, is the vsix version the same as the nuget version?

**Comment by pessimism** [comment]
Yes, both are 2.0.0

**Comment by OsirisTerje** [comment]
I've checked it and can confirm it is a bug, it does so both for a Run and a Debug Run.  I have sent information to the product group in MS about this.

**Comment by pessimism** [comment]
Thanks for the quick response and help guys!

**Comment by pvlakshm** [comment]
Thank you raising this to us. I am able to repro it. Will get it looked into.

**Comment by jeffzickgraf** [comment]
Any update on this?

**Comment by pvlakshm** [comment]
These are fixed in Visual Studio 2015 Update 2.
