### ISSUE TITLE
Exception on unobserved task crashes the test runner

### ISSUE THREAD

**Issue by jaydeboer** [nunit/nunit-vs-adapter#80]
It appears that if you have an async event handler that throws an exception, the test runner crashes and the test run is aborted.  I have a simple sample project at https://onedrive.live.com/redir?resid=52A85D37086B3CF2!3791&authkey=!ABYZo_uanh5YEEQ&ithint=file%2czip 

I would have expected the test to fail and the test run to complete.

**Comment by CharliePoole** [comment]
It would be helpful to know if this is an adapter error or an NUnit error. Can you try to run it using the nunit console or gui runner?

**Comment by jaydeboer** [comment]
Here are the results from running it in the GUI runner.  That is the first time I've used NUnit outside of Visual Studio or Xamarin Studio, but it looks to me like the test failed properly.  The GUI runner didn't crash anyway.   Is there anything else I can do to be of help?   Here is the output from the tool:
![nunitguitestresults](https://cloud.githubusercontent.com/assets/5098996/9618936/4b16e240-50d0-11e5-927a-abe8c93b0efa.PNG)

**Comment by CharliePoole** [comment]
Thanks, that will help us narrow it down.

**Comment by pvlakshm** [comment]
Thank you raising this to us. I am able to repro it. Will get it looked into.

**Comment by pvlakshm** [comment]
This is fixed in Visual Studio 2015 Update 2.

**Comment by rprouse** [comment]
@pvlakshm thanks for the update. Closing.
