### ISSUE TITLE
Test with the same name found when using TestCaseData

### ISSUE THREAD

**Issue by JXPrime** [nunit/nunit-vs-adapter#82]
We're using the TestCaseData attribute to generate tests in our solution. I've run into an issue with the VS runner where I get an error similar to the following:

A test with the same name 'Foo.Tests.Unit.Core.Services.Baz.TestMethod(SomeEntity, 0,SomeOtherEntity,-50)' already exists. This test is not added to the test window.

It seems that the nUnit GUI handles this correctly, showing tests in this form as sub-tests under the method that uses the TestCaseData. VS (or the adapter) seems to be using the name as a dictionary key, 

We could work around this by adding a dummy parameter that had a unique value to every test case data, but that seems kind of hacky. :)

I've uploaded an image that shows a screenshot of how we're preparing the TestCaseData.

![image](https://cloud.githubusercontent.com/assets/1841009/10079211/a6d2eaaa-629d-11e5-98f7-9cad377e3d6c.png)

**Comment by OsirisTerje** [comment]
I just tried the code from http://www.nunit.org/index.php?p=testCaseSource&r=2.5 to see if it would repro, even replaced one parameter with a field, but it works as it should:
![image](https://cloud.githubusercontent.com/assets/203432/10080233/c6085922-62ee-11e5-800c-89c9337f0442.png)

Can it be that you have the duplicates somewhere else ?
Also, have a look at the output pane in the Test explorer, to the bottom.  In some cases where you have duplicated test names, Test Explorer will still run them, but group them together under the same test name, and just make two outputs.

**Comment by CharliePoole** [comment]
Although it's not a true fix, I think the easiest workaround is to set the
test names in your test case data instances.

Charlie

**Comment by CharliePoole** [comment]
@OsirisTerje Could you label this as to what closing it means?

**Comment by Thierry-S** [comment]
Similar to these in nunit3-vs-adapter:
https://github.com/nunit/nunit3-vs-adapter/issues/34
https://github.com/nunit/nunit3-vs-adapter/issues/78

**Comment by aolszowka** [comment]
We are encountering this, and I agree that this is Not a Bug in the Adapter.

Therefore I have suggested an Analyzer be written to identify duplicated test names here: https://github.com/nunit/nunit.analyzers/issues/80
