### ISSUE TITLE
Long names prevent tests from being discovered

### ISSUE THREAD

**Issue by jaime-rq** [nunit/nunit-vs-adapter#83]
I get the following error while discovering tests which prevent me from getting tests from all projects.
I would expect to get the same shorted, perhaps receive a warning and then move forward.

Error:
Operation failed. The index entry of length 906 bytes for the index 'Idx_Stale_StateValue_DisplayName' exceeds the maximum length of 900 bytes.

**Comment by elbaloo** [comment]
I think this is related to https://github.com/nunit/nunit/issues/59

**Comment by CharliePoole** [comment]
nunit/nunit#59 is the underlying cause but we should handle the error better.

Can you provide a test case to reproduce this problem?

**Comment by jaime-rq** [comment]
I kept doing debug and found the test, in fact the problem was around the TestCase attribute which had chinese characters:
[TestCase("这个是中文内容, CSharp is the bast", "这是中国语内容，CSharp is the best language.", "这<del class='diffdel'>个</del>是中<del class='diffmod'>文</del><ins class='diffmod'>国语</ins>内容<del class='diffmod'>, CSharp</del><ins class='diffmod'>，CSharp</ins> is the <del class='diffmod'>bast</del><ins class='diffmod'>best language.</ins>")]

The problem I think was around the third parameter which was too long.
I removed the attribute (it had few more TestCase attributes) and I manage to get the entire test suite loaded.

**Comment by elbaloo** [comment]
Maybe try pasting the code to a [gist](https://gist.github.com/)

**Comment by jaime-rq** [comment]
didn't know about it, thanks :)
here's the link: https://gist.github.com/jaime-rq/410bc8ff2944ecd31098

**Comment by CharliePoole** [comment]
Just a note in case anyone using the nunit3-vs-adapter sees this...

In NUnit 3.0, the parameters are currently truncated to 40 chars. So with
the nunit3 adapter, the problem changes from "too long" to "duplicate ids"
in some cases.

**Comment by OsirisTerje** [comment]
I was trying to repro this, but to me this works.
What I get in the Test output window is:
     Contents of string 'ThisHasALongName("\x8FD9\x4E2A\x662F\x4E2D\x6587\x5185\x5BB9, CSharp is the bast","\x8FD9\x662F\x4E2D\x56FD\x8BED\x5185\x5BB9\xFF0CCSharp is the best language.","\x8FD9<del class=\'diffdel\'>\x4E2A</del>\x662F\x4E2D<del class=\'diffmod\'>\x6587</del><ins class=\'diffmod\'>\x56FD\x8BED</ins>\x5185\x5BB9<del class=\'diffmod\'>, CSharp</del><ins class=\'diffmod\'>\xFF0CCSharp</ins> is the <del class=\'diffmod\'>bast</del><ins class=\'diffmod\'>best language.</ins>")' exceeds max of '449', string has been truncated.

And that message seems ok.

**Comment by OsirisTerje** [comment]
I'm closing this as the issue test I have doesn't reproduce the behaviour.
