### ISSUE TITLE
NUnit failed to load

### ISSUE THREAD

**Issue by PAWatson123** [nunit/nunit-vs-adapter#84]
I’m having a "build partially succeeded" issue with this error “NUnit failed to load e:\Builds\184\CSTax\706USServices_Test\bin\Calc.Tests.dll”, but all of the unit test in this project ran and passed (all green). 

Build environment
1)	Using NUnit 2.6.4 and NUnit Test Adapter 2.0.0
2)	TFS 2013 – upgraded from 2012
3)	Visual studio 2012 and 2013 have been installed on the server
4)	I did install the NUnit Test Adapter, using the Extensions and Updates in 2013 Visual Studio
5)	Using build process templates from TFS 2012, even if I switch to the 2013 default build process templates I get the same error
6)	I tried changing the project to copy the nunit references locally (including the test adapter), they did make it to the bin folder, but still fails
7)	I used process monitor to see if I could find the failure, everything looked good, the dlls were copied from the packages folder to the bin folder.

I’m sure it has to be something in our build environment, but I do not know where to look, I need my builds to go green. Any ideas?

**Comment by CharliePoole** [comment]
Do I understand you correctly that you have a message saying Calc.Tests.dll cannot be loaded, but it is actually loaded and the tests run successfully? If that's not what you're saying, the rest of this post may not help...

Is it possible that you have both the NUnit 2 adapter and the NUnit 3 adapter installed? This is perfectly valid, but it's possible that NUnit 3 is actually issuing the message and NUnit 2 is running the tests successfully.

If that's the case, I suggest you remove the NUnit 3 adapter from any production build server. It's a CTP, after all, not a production release.

If that's not it, we can investigate in more detail.

**Comment by PAWatson123** [comment]
Yes that's what I'm saying, the tests get loaded and run successfully.
 
Yes one of our E2E test projects (a separate project and solution) are using NUnit 3.0 and the test adapter, both of these packages were added to the solution thru nuget, and they were not added the visual studio.

So
1) Is this a case were NUnit3TestAdapter 3.0.2. doesn't play nicely with NUnitTestAdapter 2.0.0? If so is this a bug and there are plans to fix this?

2) Would it be ok to update all of our NUnit 2 test to NUnit 3.0? and then this problem goes away.

**Comment by CharliePoole** [comment]
Apparently that's the case. It wasn't a bug before, but now it is... since you reported it. :-) I'm adding this to the next CTP.

WRT converting all your tests to NUnit 3.0, in your place, I would wait. By calling it a beta test, the publishers of the software (us) are saying it's not yet ready for production. Presumably, we have reasons for that. :-)

In fact, the problem is mainly one of stability rather than of bugs. Things can change quite readily from beta to beta. You may rely on a feature that disappears in a later release. It's less likely now that we are (hopefully) on the last beta, but things are still changing.

If you are using the adapter in your CI build, is it possible for you to simply switch to running the console runner? That's almost always how I do it with my clients.

**Comment by CharliePoole** [comment]
In the case of the NUnit 2 adapter, the issue is that the version seems to be hard-coded in the message. This should be an easy fix.

I'm creating a separate issue for the NUnit 3 adapter, since it's a different project.

**Comment by PAWatson123** [comment]
I removed our E2E project (the one using NUnit 3.0 ) off the build server, now all my builds are green again. 
Thanks for the help!

**Comment by nbelley** [comment]
Any ETA on that? I didn't have any problem before I update to Visual Studio 2015 and TFS 2015, now all my tests are runned and successful, but I have a «NUnit failed to load C:\Builds\1\xxx\DEV.Build - Server\bin\XXX.Tests.dll » for each test projects in the solution. 

Any workaround?

**Comment by CharliePoole** [comment]
I'm working on it this week. No workaround that I can think of, however.

**Comment by CharliePoole** [comment]
My mistake. I thought we were on the NUnit 3 Adapter issue. That's what I'm working on.

**Comment by nbelley** [comment]
Oups, my mistake also, if it won't be a problem in NUnit 3, I'll be ok with it also.

**Comment by CharliePoole** [comment]
This is designated milestone 2.2, but the version has been changed to 2.1.0.7. Is it intended for a private build for a user?

**Comment by Aswilli4** [comment]
Is there any update on this issue? Once I added a second dll I am getting this:

    NUnit Adapter 3.0.10.0: Test execution started
    Running all tests in     C:\(FilePath)\new.dll
    NUnit failed to load C:\(FilePath)\new.dll
    Running all tests in C:\(FilePath)\old.dll
    NUnit3TestExecutor converted 28 of 28 NUnit test cases

**Comment by CharliePoole** [comment]
Are both dlls using NUnit 3? Is 28 the correct number of cases for the old dll?

**Comment by CharliePoole** [comment]
@OsirisTerje This issue is getting a lot of NUnit 3 discussion, even though it is filed against the NUnit VS Adapter, which is for NUnit V2. Can we do something to clarify this for the users?

**Comment by Aswilli4** [comment]
@CharliePoole  Realized I was going about this the wrong way. This has been resolved updated my Assembly file with 
      [assembly: NUnit.Framework.Parallelizable(NUnit.Framework.ParallelScope.Fixtures)]


and fixed everything!

**Comment by CharliePoole** [comment]
@Aswilli4 Hmmm... Are you by chance using a third-party framework that extends the NUnit framework?

**Comment by Aswilli4** [comment]
@CharliePoole  I am using VS2015 up to this point I didnt realize the newly added features that NUnit3 had. Simply adding that assembly file changed everything.

**Comment by CharliePoole** [comment]
The reason for my question is that some third party test frameworks extend NUnit, referencing NUnit 3. If you use such a framework, then your assembly may have no direct reference to NUnit 3. If adding the Parallelizable attribute created the first reference to NUnit 3, that would explain why it works.

But if you are not using such a third party framework, forget everything I just wrote. :-)
