### ISSUE TITLE
Extreme delay in running tests after upgrading to VS2015

### ISSUE THREAD

**Issue by mgregory22** [nunit/nunit-vs-adapter#85]
I created a 2 project solution in VS2013 community edition with Nunit.  I have 136 tests in one project and 10 tests in the other.  I would "Run All" and all the tests would run in one second.

A couple weeks ago I upgraded to VS2015.  I had to make a few tweaks to get Nunit working again (I think I just had to reinstall it).  It now works, but when I do a "Run All", it will run the one project's 136 tests very quickly, but then it will wait for over a minute to run the 10 tests in the other project.

If I set the Test Explorer's Group By setting to Project and run each project individually by right-clicking, each project runs instantaneously.  But if I try to run them all together via the "Run All" command, it has a weird delay of over a minute when switching between projects.

I think it must be the Nunit VS Adapter that's the problem, but I'm not entirely sure and I apologize for that.  I'm still very new to Nunit stuff.

The project is at https://github.com/mgregory22/Priorities .  It's a small toy project.

**Comment by AdamCooperLivingLens** [comment]
I'm seeing the same issue, tests run quickly when run by assembly but there is an extremely large delay when moving from one assembly to the next when run via "Run All". The delay can be multiple minutes.

**Comment by OsirisTerje** [comment]
Can you please recheck this with Visual Studio 2015 Update 1 ?    There are several issues resolved there that might positively affect this.  
@mgregory22 :  I tried your project, and it works fine for me, no delays.

**Comment by AdamCooperLivingLens** [comment]
Issue is resolved for me with Update 1

**Comment by mgregory22** [comment]
Update 1 resolved it for me too.  You bet.  Thanks for looking into it.
