### ISSUE TITLE
Exception in object Finalizer crashes TE.ProcessHost.Managed.exe cancelling test runs

### ISSUE THREAD

**Issue by LordJZ** [nunit/nunit-vs-adapter#88]
Visual Studio 2015. This is also reproduced on NUnit v3 adapter.

Consider this piece of code:
```C#
[TestFixture] public class UnitTest1
{
    class WTF {
        ~WTF() { throw new Exception(); }
    }

    WTF wtf;

    [TestFixtureSetUp] public void SU() {
        wtf = new WTF();
    }

    [Test] public void Test() {
        Assert.AreEqual(2, 2);
    }

    [TestFixtureTearDown] public void TD() {
        wtf = null;
        GC.Collect();
        GC.WaitForPendingFinalizers();
    }
}
```
(Full solution [attached](https://github.com/nunit/nunit-vs-adapter/files/40641/NUnitAdapterCrash.xlsx) - treat .xlsx as .zip archive)

When running all tests, this test spec succeeds when run in:
* NUnit-Console.exe
* NUnit.exe
* R# Test Runner

But test does not run when run in VS Test Explorer using NUnit VS Adapter. The process TE.ProcessHost.Managed.exe crashes because of an exception in object finalizer on GC Finalizer Thread.

Not sure if anything can be done here, though, if it's a VS bug.

**Comment by OsirisTerje** [comment]
This should be fixed in VS 2015 Update 1 RC, can you check ?

**Comment by OsirisTerje** [comment]
I have this confirmed now, but it might be in the VSTest system itself, so I have reported this in to the PG, and will await their response.

**Comment by OsirisTerje** [comment]
The same issue, different repro, is here:  https://github.com/nunit/nunit-vs-adapter/issues/80

**Comment by pvlakshm** [comment]
Thank you raising this to us. I am able to repro it. Will get it looked into.

**Comment by pvlakshm** [comment]
This is fixed in Visual Studio 2015 Update 2.

**Comment by rprouse** [comment]
@pvlakshm thanks for the update. We will close this issue.
