### ISSUE TITLE
test widget doesnt appear when using TestCaseSource

### ISSUE THREAD

**Issue by joshbouganim** [nunit/nunit-vs-adapter#91]
I'm not sure what to call it, but i am referring to this check icon, when clicked, expands to a bigger action menu:

http://snag.gy/qxQIe.jpg

it does not appear when using TestCaseSource:

http://snag.gy/rhPlN.jpg

i understand why this happens because testcasesource renames the unit test but is there anything that the test adapter can do to still make the widget appear?

**Comment by CharliePoole** [comment]
Is this the same as #29?

**Comment by OsirisTerje** [comment]
Yes, this is the same, it has been reported to MS PG.
Closing this as a duplicate
