### ISSUE TITLE
Attempt to load assembly with unsupported test framework

### ISSUE THREAD

**Issue by StanBPublic** [nunit/nunit-vs-adapter#93]
I wonder why I get this error:

```
Unit VS Adapter 2.0.0.0 discovering tests is started
Attempt to load assembly with unsupported test framework in  C:\...\X.IntegrationTests.dll
NUnit VS Adapter 2.0.0.0 discovering test is finished
```
The assembly in question has reference to nunit 3.0.5813.39031. Is this version not supported?

**Comment by OsirisTerje** [comment]
It seems like the X.IntegrationTests.dll you have is written using a different framework, it can be then also be NUnit3.  If you created this recently, and just installed NUnit, you will get NUnit 3, not NUNit 2, and then you need to install the NUnit 3 adapter (https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d)  .  The NUnit 2 adapter can run at the same time, but it will give this warning.

**Comment by StanBPublic** [comment]
It worked, thank you (I thought that installing NUnit3 adapter uninstalls 2..)

**Comment by shishirroy1982** [comment]
Its working for me also. Although I have removed all the references of NUnit2

**Comment by ajshehan** [comment]
Worked for me as well. Thanks
