### ISSUE TITLE
Explicit tests appear as warnings in NUnit 3.0

### ISSUE THREAD

**Issue by isaacllopisaracil** [nunit/nunit-vs-adapter#94]
This issue comes from this other one for reference:
https://github.com/nunit/nunit/issues/50

According to the definition of the Explicit tests in NUnit:
>If a test or fixture with the Explicit attribute is encountered in the course of running tests, it is skipped unless it has been specifically selected by one of the above means. The test does not affect the outcome of the run at all: it is not considered as ignored and is not even counted in the total number of tests. In the gui, the tree node for the test remains gray and the status bar color is not affected.
>(https://github.com/nunit/nunit/wiki/Explicit-Attribute)

However, after upgrading my NUnit tests to 3.0 and the VS Adapter, the tests marked as Explicit show as Warnings instead, marking my tests list with a yellow-orange warning error color.

**Comment by OsirisTerje** [comment]
Moved to NUnit3 adapter
Closed here.
