### ISSUE TITLE
Request: Collapse All button

### ISSUE THREAD

**Issue by isaacllopisaracil** [nunit/nunit-vs-adapter#98]
It so often happens that the VS Adapter shows the first element in the test tree uncollapsed and the rest collapsed, and if I'm working with another element in the tree (another assembly or class) I have to scroll all the way down.

VS added the "Collapse All" button in the Solution Explorer for situations like this. Can the test adapter for VS studio allow for this too?

**Comment by CharliePoole** [comment]
The test window is part of visual studio. The adapter can only run and report tests.

**Comment by CharliePoole** [comment]
The test window is part of visual studio. The adapter can vonly run and report tests.
